### ISSUE TITLE
Keep state on Process-Death

### ISSUE THREAD

**Issue by fablue** [sellmair/kompass#4]
Kompass doesn't keep the current state on process-death. 
Routing to a certain destination, terminating the app, re-opening will lead route to the last destination. This could be changed by separating lambdas and destinations from inside the backstack and serializing the backstack to the onSaveInstance bundle.

**Comment by youfacepalm** [comment]
Should the size limit of the bundle need to be considered when you go through this approach?

Related [SO Question](https://stackoverflow.com/questions/8552514/is-there-some-limits-in-android-bundle)

**Comment by fablue** [comment]
Hey, thanks for the comment! Honestly, I didn't even know about this issue =/

Currently, I think we should not care 🤔 
If you are passing such big data to your destination, then maybe the approach of bundles itself is not correct. 

I personally think one should just pass a list of id's to bundles/Destinations not the complete list of objects itself and that the ViewModel is responsible for getting the data later. 

But I also think that it would be pretty cool if the library (later on) could handle such a case! The only thing is:

I am pretty proud, that Kompass could theoretically be used with fragments/activities that do not know about Kompass, because it put's the arguments into the bundle like a human would do it too (and should later be more configurable). We would break this feature/idea when we do not implement it correctly? 

@youfacepalm What do you think: How important is this issue? 🤔

**Comment by youfacepalm** [comment]
@fablue What you said makes sense. I think focusing on state retention during process death should be the top priority for now.

Great library btw 👍

**Comment by sellmair** [comment]
@youfacepalm I am glad you appreciate it 😌
