### ISSUE TITLE
Decouple Android dependencies

### ISSUE THREAD

**Issue by heinrichreimer** [sellmair/kompass#47]
I believe, Kompass is a great router not only for Android.
If we decouple the Android-related implementation detail into separate modules, we could use Kompass also for other frameworks.
I guess that would have a clear benefit and shouldn't even be too complicated as the only Android-dependent stuff is `Bundle` and how to set a sail, which of course can be generalized using some clever interfaces and modules.

Clearly, this would break some code, but I would like to investigate the idea further.

**Comment by sellmair** [comment]
I really like this idea!
Maybe we can use this in combination with kotlin/native and kotlin-multiplatform? 🤔

**Comment by heinrichreimer** [comment]
Sure, even though that might involve a bit more effort.
Have tried to work with Kotlin multi platform and got the feeling that if you have any dependencies, you're going to have a tough job decoupling them.
Does Kompass use any third-party libraries?

**Comment by sellmair** [comment]
#49
