### ISSUE TITLE
Sample: LoginProcessingFragment can get stuck in loading state forever

### ISSUE THREAD

**Issue by Zhuinden** [sellmair/kompass#73]
https://github.com/sellmair/kompass/blob/ceed98827b5aa5687df78b83d9de8060ffc7e0dc/android-example--fragment/src/main/java/io/sellmair/kompass/android/example/viewmodel/LoginProcessingViewModel.kt#L37-L39

Because of `viewModel.stop()` in `onPause`, if app is put to background and brought to foreground while `LoginProcessingFragment` is on front, then the app gets stuck here forever.

You might want to consider some form of observable that the is bound to `onStart/onStop` rather than `onPause` (and no counterpart).

After rotation, it still gets stuck on the screen:

<img width="265" alt="Screenshot 2019-05-06 at 13 39 37" src="https://user-images.githubusercontent.com/11718392/57222867-76fd4280-7004-11e9-9831-b657e6e2b632.png">

**Comment by sellmair** [comment]
Thanks a lot for reporting 👍 
Will fix this on Tuesday!

**Comment by isaac-udy** [comment]
I've got a fix for this - will open a PR when I can. 

`viewModel.stop()` isn't actually necessary, as the `onCleared` will handle the case where the handler needs clearing.
